[package]
name = "geometric-features"
version = "0.1.0"
edition = "2021"

[lib]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32"

[dev-dependencies]
rand = "0.8"
flame = "0.2"